### PR TITLE
Add bash script to rename contents of project

### PR DESCRIPTION
**Pull request by ianoshorty**
I've written renamer.sh which is a simple shell script to rename the various "plugin-name" / "Plugin_Name" / "plugin_name" instances in the project, and do some simple modifications to plugin_name.php to match.

The net result is a fully renamed project and content ready for new plugin develop. Hope its useful!

### CODE REVIEW

**Comment by DevinVinson** [comment]
Awesome! I need to test and play with it a bit but this is definitely something I've wanted to include for a long while.

**Comment by elvismdev** [comment]
+1
This web app does something similar http://wppb.me/
It will be great to have a `.sh` script that accomplish the same here within this project.

**Comment by DevinVinson** [comment]
Finally got some time to play with this and test everything out. Thank you so much for contributing! The only change I may make at some point is the name to something like "build" or simply "rename-script".

Anyone have any thoughts on keeping or removing the file after renaming? I added in a `rm renamer.sh` into the very end of the if confirmation = y  which seems to do the trick but I'm on the fence if it is needed or feels right.

**Comment by DevinVinson** [comment]
Just noticed this also renames the get_plugin_name method which gets a bit weird if renamed. Happen to know how to skip a specific instance in a file by chance 😄

**Comment by elvismdev** [comment]
Any advance about this PR or when it's going to be ready for master? Thank you!

**Comment by DevinVinson** [comment]
Maybe next month? I don't like the get_plugin_name re-naming since it can cause confusion and is something that was able to get solved with the wppb.me implementation.

**Comment by ianoshorty** [comment]
Hey all.
I just realised I accidentally had this chat muted and assumed it was quiet. I'm happy to review the PR, update it and make any changes you would like! I will take a look at the weekend for you.
Cheers,
Ian.

**Comment by simonh1000** [comment]
I'd love to see this added. With the wordpress API it is now possible to build stuff without using PHP (and object oriented paradigms). So I arrived at this repo knowing nothing about PHP and classes and just wanting to get a single page up and running from which I could do everything else using a frontend js setup (Elm or Vue). The original repo is findable by wordpress, but I've not mananged to rename anything yet in a way that means wordpress can refind it

**Comment by michaelmob** [comment]
I will take a crack at this with bash, but what do you think about also having a Python script? Then it would be able to run on any OS that can run Python.

**Comment by otakupahp** [comment]
SO this was never done?

**Comment by DevinVinson** [comment]
I don't think so.

**Pull request closed without merging**
