### PR TITLE
refactor using native add_action and add_filter functions

### PR DESCRIPTION
**Pull request by yaronguez**
See issue: https://github.com/DevinVinson/WordPress-Plugin-Boilerplate/issues/396

By using native add_action and add_filter functions you're able to use IDE benefits and stick to WordPress conventions, decreasing the learning curve to new plugin developers.

### CODE REVIEW

**Comment by DevinVinson** [comment]
I've been on the fence about the loader from the start so I am always open for a change there.

Do you have any plugins using your updated class to get a feel for your usage?

**Comment by yaronguez** [comment]
Sorry for the delay. The only plugin I'm using this in right now is a private BitBucket repo that is at its limit for number of users I can grant access to. I can email you a zip file if you'd like. 

Out of curiosity, why did you decide to instantiate each object and defining its hooks in one class setup class as opposed to using a singleton pattern where the hooks are defined for each class in that class's constructor? Is it to keep all of the plugin's hooks in one place so it's easier to determine what it's doing?

**Comment by schrapel** [comment]
@yaronguez singleton is an anti pattern and defining hooks in the constructor makes it hard to write automated tests. 

I think keeping hooks all in one place is a bad idea for large codebases. I prefer using the observer pattern where each subscriber has an interface that defines a get_hooks function. The manager is then responsible for registering all the hooks

**Comment by slushman** [comment]
@schrapel Do you have an example plugin using that structure? I'd be interested to see how that works.

@yaronguez RE: singletons - the previous version of the boilerplate used singletons and this version was intended to get away from using it.

**Comment by DevinVinson** [comment]
@schrapel That is essentially what I prefer doing these days as well.

I did not originally write this version of the boilerplate but am a maintainer of it for now.

**Comment by schrapel** [comment]
@slushman it is explained really well here https://carlalexander.ca/design-system-wordpress-event-management/

@DevinVinson I don't think it's something that should be done here but I also don't think the loader should really be left in its current form either.

**Comment by yaronguez** [comment]
@schrapel That makes sense about not defining hooks in the constructor but why is the singleton pattern considered an anti-pattern? 

I think that what you're describing could be done with a slight refactor of my pull request. Each `define_[foo]_hooks` method of the `Plugin_Name_Hooks` class could be moved into its associated `Plugin_Name_[Foo]` class and renamed to `define_hooks`.  The parent setup class would add each `define_hooks` method to the `plugin_name_load_hooks` action and execute `do_action('plugin_name_load_hooks')` on run. At that point it might even be overkill to have a `Plugin_Name_Hooks` class at all.

**Comment by yaronguez** [comment]
I'm actually meeting up with Carl Alexander this Thursday through the San Diego Advanced WordPress group. I can get his thoughts on this.

**Comment by yaronguez** [comment]
Our meeting with Carl is streaming live if you're curious... https://www.facebook.com/groups/advancedwp/permalink/1246462408749304/

**Comment by yaronguez** [comment]
After talking this over with Carl and other devs last night, I'd like to revisit the need to define all of your hooks at one time when the Run command is launched. The hook system doesn't care when a hook is created so why should the boilerplate go out of its way to group these events together?

The question of whether to define all of your hooks in one class (be it a Plugin_Name_Hooks class or the core Plugin_Name class) or to define them in the classes where each method is defined (e.g. Plugin_Name_Public->register_hooks()) is really a matter of personal preference. But at the very least I think we can do away with the custom Loader method.

Thoughts?

p.s. if you did try to watch the video stream last night, it got cut off when the videographer's phone died and was continued on another phone here: 
https://www.facebook.com/groups/advancedwp/permalink/1246482798747265/

**Comment by schrapel** [comment]
Out of your suggested option I'd go with a register hooks method in each
class but then you'll still need some form of loader to register these

**Comment by slushman** [comment]
I've refactored a plugin and removed the loader. It works nicely and simplifies things like having a theme remove actions and filters to customize the output of the plugin. But I still prefer to have all the hooks in one place though. Just a personal preference.

**Comment by yaronguez** [comment]
I just refactored mine and am submitting a new pull request.

**Pull request closed without merging**
