### PR TITLE
Setup

### PR DESCRIPTION
**Pull request by franz-josef-kaiser**
In short: Moved everything to `uninstall.php`. Imho that file should be renamed to `setup.php`. Or if someone wants to _really, really_  use that crap, which is called "WordPress Coding Standards", then it should be `class-plugin-name-setup.php`.

I moved everything - including the callback hooked to the `wpmu_new_blog` hook - into that file. The file itself contains a class. All the logic that has previously been in place (like looping though blogs/blog IDs and calling single site actions/callbacks) have been moved as well. This makes the main file much more consistent.

### CODE REVIEW

**Comment by adsperclick** [comment]
Which file I used, need to put additional function to make a add_shortcode()?

**Comment by swinc** [comment]
I implemented the checks here for deleting a plugin and got seriously stuck on the `check_admin_referer()` function. It simply would not pass the check.

For anyone else running into this:

1. It's actually the [`check_ajax_referer()`](https://developer.wordpress.org/reference/functions/check_ajax_referer/) function you should be using.

2. The correct "action" to pass to this function was `updates`, *not* `delete-selected` as is shown in the delete link URL, or even `delete-plugin` as is shown in the AJAX form submission.

At least that finally worked for me.

**Comment by smileBeda** [comment]
@swinc - Thank you for your findings.

It is utter weird what happens here.

1. [this](https://developer.wordpress.org/reference/functions/check_ajax_referer/) clearly states that the method will check for the `action` and the action here is neither `delete-selected` (as in the delete URL `action` parameter), neither `update` (I have no idea how you discover this is the actual working one), but it is `delete-plugin` as visible when we dump `$_REFERER`!
2. However - go figure why - it works only when you do exactly as you said above `check_ajax_referer( 'updates', '_ajax_nonce');`

How did you find out about this?
I [opened a ticket](https://wordpress.org/support/topic/check_admin_referer-always-returns-false/) in WP Support perhaps someone can clarify it there - but it is really leaving me a tad confused. 
The action is defined more than clear in the Referer, once again different in the URL, and at the end we need to use something totally un-intuitive as update. It is not an update that is happening! 

Strange.

**Comment by swinc** [comment]
@TukuToi - My recollection is I looked at the `action` stored with the nonce in the WP database and worked backwards. But I agree this appears to be a bug, and when they fix it my code will break. :)

**Comment by smileBeda** [comment]
@swinc - perhaps this will sooth your worries too:
https://wordpress.org/support/topic/check_admin_referer-always-returns-false/

It is expected, and the only way to find the "action" would be either looking at the code or as you did checking up in the DB.
It was helpful for me, I really was a but confused about this all, now it makes some sort of sense, or lets say, at least I know how to deal with it ;)

**Pull request closed without merging**
