### PR TITLE
Adding a version constant

### PR DESCRIPTION
**Pull request by jonathanbossenger**
Adds a PLUGIN_VERSION constant to the main plugin file. As this is usually the file where the version gets updated in the plugin header, it makes it easier to update the actual plugins version number in the same file.

### CODE REVIEW

**Comment by DevinVinson** [comment]
Seems like a pretty obvious and solid update. Any generators based on the plugin will need to update to find and replace `PLUGIN_VERSION`.

I'll leave this up for a few days in case anyone has some glaring issue we aren't seeing but otherwise 👍

**Comment by jonathanbossenger** [comment]
@DevinVinson when/if this is approved my plan is to fix any issues with #371 with some help from [this script](https://github.com/hlashbrooke/WordPress-Plugin-Template/blob/master/build-plugin.sh)

**Comment by jonathanbossenger** [comment]
@DevinVinson just a friendly nudge on this PR, no rush, but I'm keen to submit the build-plugin PR as well ;-)

**Comment by mario-neuhold** [comment]
Would it make sense to add the Plugin_Name to the version constant? So if you're using more than one plugins with this boilerplate at the same time the constants won't interfere.

**Comment by DevinVinson** [comment]
It should definitely have a comment to be prefixed.

**Pull request merged**
