### PR TITLE
Major improvements

### PR DESCRIPTION
**Pull request by pcfreak30**
The following PR merges #377 and #371.

It also:
-  Reformats code using PHPStorm's Wordpress formatter profile
-  Adds an autoloader and uses a filter to allow more paths
-  Adds an init function to launch instance on plugins_loaded
-  Removes hooks/filters from loader after processing, then resets array keys. This allows the loader to become a "queue" to process multiple times.

### CODE REVIEW

**Comment by DevinVinson** [comment]
Excellent from the initial look over. Going to need to sit down and go through it all piece by piece.

Any specifics you have or had hesitations on or are unsure about?

**Comment by pcfreak30** [comment]
I had to do this to not rewrite the code a ton of times. I took the singleton function wrapper idea from woocommerce that uses `WC()`. Im not sure if using a loader to even queue the actions/filters is the best idea, but ATM it makes it impossible to run it several times. Lastly its an overall good idea to start the plugin on plugins_loaded. I myself needed to know the existence of other plugins, so I changed the priority to 11 in a recent plugin. All changes should be backwards compatible to 5.2/5.3. Some unneeded things have been removed.

Right now this is in 2 plugins of mine on wp.org. One of which I just did a major refactor to add said changes. https://github.com/pcfreak30/rocket-async-css and https://github.com/pcfreak30/rocket-background-cache

**Comment by DevinVinson** [comment]
Looks like there are still some todos left on this. I'm open to the approach but right now the constants aren't being used in place of the now removed get_plugin_name and get_version methods fully.

I've got this open as a branch locally and really appreciate the initial shove forward this provides so far 👍

**Comment by pcfreak30** [comment]
@DevinVinson right now I don't have time to clean this up. But hopefully this will allow work to get completed on these ideas.

**Comment by benoitchantre** [comment]
Would it be possible to split this pull request in two, in order to merge the approved pieces and to continue the work in another pull request?

@DevinVinson what are the approved pieces?

**Comment by DevinVinson** [comment]
@barryceelen Nothing in this is approved for merging in. If anything would require rewriting all the tutorials that have come out over the years for the boilerplate I would make it a complete rewrite from the ground up which this is on the road to being.

I'm not so concerned with keeping a clean git repo for this project because each PR serves as such a good learning tool on where you can go with the boilerplate.

**Comment by pcfreak30** [comment]
@DevinVinson see https://github.com/pcfreak30/composepress-starter, this is where I have ended up.

**Pull request closed without merging**
